import "server-only";
import { env as workerEnv } from "cloudflare:workers";

/**
 * Runtime environment for server code.
 *
 * `worker-configuration.d.ts` (generated by `wrangler types`) describes the
 * bindings and plain vars declared in wrangler.jsonc. Secrets are deliberately
 * absent from that file — they are set with `wrangler secret put` — so they are
 * declared here as optional strings and read through checked accessors.
 */
export interface AppEnv extends Env {
  SESSION_SECRET?: string;
  SSLCOMMERZ_STORE_ID?: string;
  SSLCOMMERZ_STORE_PASSWORD?: string;
  TURNSTILE_SECRET?: string;
  NEXT_PUBLIC_TURNSTILE_SITE_KEY?: string;
  EMAIL_PROVIDER?: string;
  EMAIL_FROM?: string;
  RESEND_API_KEY?: string;
  SMTP_HOST?: string;
  SMTP_PORT?: string;
  SMTP_USER?: string;
  SMTP_PASSWORD?: string;
  MAP_PROVIDER?: string;
  NEXT_PUBLIC_MAP_TILE_URL?: string;
  NEXT_PUBLIC_MAP_ATTRIBUTION?: string;
  NEXT_PUBLIC_IMAGE_BASE_URL?: string;
}

export function getEnv(): AppEnv {
  return workerEnv as unknown as AppEnv;
}

export function getDb(): D1Database {
  const db = getEnv().DB;
  if (!db) throw new Error("D1 binding `DB` is not configured");
  return db;
}

export function getPropertyImagesBucket(): R2Bucket {
  const bucket = getEnv().PROPERTY_IMAGES;
  if (!bucket) throw new Error("R2 binding `PROPERTY_IMAGES` is not configured");
  return bucket;
}

/**
 * Reads a required secret. Throwing at the point of use (rather than at module
 * load) keeps unrelated pages working when, say, only the email provider is
 * unconfigured.
 */
export function requireSecret(name: keyof AppEnv): string {
  const value = getEnv()[name];
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`Missing required secret: ${String(name)}`);
  }
  return value;
}

export function isProduction(): boolean {
  return getEnv().APP_ENV === "production";
}

export function siteUrl(): string {
  return (getEnv().NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000").replace(/\/$/, "");
}

/**
 * The server-side price of one contact unlock, in whole BDT.
 *
 * SECURITY: this is the ONLY place the unlock price is decided. It is never
 * read from a request body, a query string, or a hidden form field.
 */
export function contactUnlockPriceBdt(): number {
  const raw = getEnv().CONTACT_UNLOCK_PRICE_BDT;
  const parsed = Number.parseInt(String(raw ?? "50"), 10);
  if (!Number.isFinite(parsed) || parsed <= 0) return 50;
  return parsed;
}
